Greenmarket2.0/Greenmarket/Greenmarket/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path
from crud import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("registro/", views.registro, name="registro"),
    path("iniciosesion/", views.iniciosesion, name="iniciosesion"),
    path("blog/", views.blog, name="blog"),
    # tienda para proveedores
    path("tiendaP/", views.mostrar_productosP, name="tiendaP"),
    # cerrar sesion
    path("cerrarsesion/", views.signout, name="cerrarsesion"),
    # cliente
    path(
        "iniciosesion/perfilC/",
        views.crear_perfil_cliente,
        name="perfilC",
    ),
    path(
        "iniciosesion/cliente/editarperfil",
        views.editar_perfil_cliente,
        name="Cliente",
    ),
    # proveedor
    path(
        "iniciosesion/perfilP/",
        views.crear_perfil_proveedor,
        name="perfilP",
    ),
    path(
        "iniciosesion/proveedor/editarperfil",
        views.editar_perfil_proveedor,
        name="Proveedor",
    ),
    path(
        "detalleproducto/<int:producto_id>/",
        views.detalle_producto,
        name="detalleproducto",
    ),
    # crud productos
    path("listar-productos/", views.listar_productos, name="listar_productos"),
    path("crear-producto/", views.crear_producto, name="crear_producto"),
    path(
        "editar-producto/<int:producto_id>/",
        views.editar_producto,
        name="editar_producto",
    ),
    path(
        "eliminar-producto/<int:producto_id>/",
        views.eliminar_producto,
        name="eliminar_producto",
    ),
    # carrito -------------------
    path("carro/", views.mostrar_productos, name="carro"),
    path("agregar/<int:producto_id>/", views.agregar_carro, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_carro, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_carro, name="restar"),
    path("limpiar/", views.limpiar_carrito, name="limpiar"),
    # orden de compra
    path("ordencompra", views.confirmar_compra, name="orden"),
    # trueque
    path(
        "trueque/<int:proveedor_id>/<int:producto_id>/", views.trueque, name="trueque"
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Greenmarket2.0/Greenmarket/crud/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "auth_group"


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey("AuthPermission", models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = "auth_group_permissions"
        unique_together = (("group", "permission"),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    content_type = models.ForeignKey("DjangoContentType", models.DO_NOTHING)
    codename = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "auth_permission"
        unique_together = (("content_type", "codename"),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128, blank=True, null=True)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150, blank=True, null=True)
    first_name = models.CharField(max_length=150, blank=True, null=True)
    last_name = models.CharField(max_length=150, blank=True, null=True)
    email = models.CharField(max_length=254, blank=True, null=True)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = "auth_user"


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = "auth_user_groups"
        unique_together = (("user", "group"),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = "auth_user_user_permissions"
        unique_together = (("user", "permission"),)


class Cliente(models.Model):
    id_cliente = models.BigAutoField(primary_key=True)
    id_sexo = models.ForeignKey("Sexo", models.DO_NOTHING, db_column="id_sexo")
    id_estado = models.ForeignKey(
        "EstadoCivil", models.DO_NOTHING, db_column="id_estado"
    )
    id_comuna = models.ForeignKey("Comuna", models.DO_NOTHING, db_column="id_comuna")
    rut_cliente = models.BigIntegerField()
    dv_cliente = models.CharField(max_length=1)
    pnombre = models.CharField(max_length=50)
    snombre = models.CharField(max_length=50, blank=True, null=True)
    apellidom = models.CharField(max_length=50)
    apellidop = models.CharField(max_length=50)
    telefono = models.BigIntegerField()
    edad = models.BigIntegerField()
    direccion = models.CharField(max_length=50)
    correo = models.CharField(max_length=50)
    id_usuario = models.ForeignKey(
        "CustomUser", models.DO_NOTHING, db_column="id_usuario"
    )

    class Meta:
        managed = False
        db_table = "cliente"

    def __str__(self):
        return f"{self.pnombre} "


class Comuna(models.Model):
    id_region = models.ForeignKey("Region", models.DO_NOTHING, db_column="id_region")
    id_comuna = models.BigAutoField(primary_key=True)
    descripcion = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = "comuna"

    def __str__(self):
        return self.descripcion


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200, blank=True, null=True)
    action_flag = models.IntegerField()
    change_message = models.TextField(blank=True, null=True)
    content_type = models.ForeignKey(
        "DjangoContentType", models.DO_NOTHING, blank=True, null=True
    )
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = "django_admin_log"


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100, blank=True, null=True)
    model = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "django_content_type"
        unique_together = (("app_label", "model"),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255, blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = "django_migrations"


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField(blank=True, null=True)
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = "django_session"


class Envio(models.Model):
    id_envio = models.BigAutoField(primary_key=True)
    descripcion = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = "envio"

    def __str__(self):
        return self.descripcion


class EstadoCivil(models.Model):
    id_estado = models.BigAutoField(primary_key=True)
    descripcion = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = "estado_civil"

    def __str__(self):
        return self.descripcion


class GreenmarketappUsuario(models.Model):
    id = models.BigAutoField(primary_key=True)
    username = models.CharField(unique=True, max_length=100, blank=True, null=True)
    password = models.CharField(max_length=100, blank=True, null=True)
    tipo_perfil = models.CharField(max_length=10, blank=True, null=True)
    rut_cliente = models.BigIntegerField()
    rut_proveedor = models.BigIntegerField()

    class Meta:
        managed = False
        db_table = "greenmarketapp_usuario"


class LoginUser(models.Model):
    id = models.BigAutoField(primary_key=True)
    username = models.CharField(max_length=30, blank=True, null=True)
    password = models.CharField(max_length=30, blank=True, null=True)
    user_type = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "login_user"


class OrdenCompra(models.Model):
    id_compra = models.BigAutoField(primary_key=True)
    id_proveedor = models.BigIntegerField()
    id_envio = models.ForeignKey("Envio", models.DO_NOTHING, db_column="id_envio")
    id_pago = models.ForeignKey("Pago", models.DO_NOTHING, db_column="id_pago")
    id_cliente = models.BigIntegerField()
    fecha_compra = models.CharField(max_length=50)
    cant_compra = models.BigIntegerField()
    valor_total = models.BigIntegerField()
    valor_neto = models.FloatField()
    iva = models.FloatField()

    class Meta:
        managed = False
        db_table = "orden_compra"


class OrdenTrueque(models.Model):
    id_otrueque = models.BigAutoField(primary_key=True)
    origen = models.CharField(max_length=50)
    destino = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=50)
    cant_recibida = models.BigIntegerField()
    cant_enviada = models.BigIntegerField()
    itrueque = models.CharField(max_length=50)
    dtrueque = models.CharField(max_length=50)
    fecha_trueque = models.DateField()
    prod_enviado = models.BigIntegerField()
    prod_recibido = models.BigIntegerField()

    class Meta:
        managed = False
        db_table = "orden_trueque"


class Pago(models.Model):
    id_pago = models.BigAutoField(primary_key=True)
    descripcion = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = "pago"

    def __str__(self):
        return self.descripcion


class Proveedor(models.Model):
    id_proveedor = models.BigAutoField(primary_key=True)
    rut_proveedor = models.BigIntegerField()
    dv_proveedor = models.CharField(max_length=1)
    id_comuna = models.ForeignKey(Comuna, models.DO_NOTHING, db_column="id_comuna")
    edad = models.BigIntegerField()
    nombre_proveedor = models.CharField(max_length=50)
    apellidom = models.CharField(max_length=50)
    apellidop = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50)
    nombre_tienda = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=50)
    telefono = models.BigIntegerField()
    id_estado = models.ForeignKey(EstadoCivil, models.DO_NOTHING, db_column="id_estado")
    id_sexo = models.ForeignKey("Sexo", models.DO_NOTHING, db_column="id_sexo")
    correo = models.CharField(max_length=50)
    id_usuario = models.ForeignKey(
        "CustomUser", models.DO_NOTHING, db_column="id_usuario"
    )

    class Meta:
        managed = False
        db_table = "proveedor"

    def __str__(self):
        return self.nombre_tienda



Greenmarket2.0/Greenmarket/crud/templates/blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title>{% block title %}GreenMarket{% endblock %}</title>
  
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
</head>

<body>

  <div class="fondo">

    <nav class="navbar navbar-expand-lg fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <img src="{% static 'img/gmlogo-largo1.png' %} " width="300" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#">Inicio</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'iniciosesion' %}">Iniciar Sesión</a>
              </ul>
        </div>
      </div>
    </nav>

    {% block content %}
    
    <div id="carouselE" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselE" data-bs-slide-to="0" class="active" aria-current="true"
            aria-label="slide 1"></button>
          <button type="button" data-bs-target="#carouselE" data-bs-slide-to="1" aria-current="true"
            aria-label="slide 2"></button>
          <button type="button" data-bs-target="#carouselE" data-bs-slide-to="2" aria-current="true"
            aria-label="slide 3"></button>
        </div>
  
        <div class="carousel-inner" heigh="1000px">
  
          <div class="carousel-item active">
            <img src="{% static 'img/carrusel1.png' %}" class="d-block w-100" alt="">
            <div class="carousel-caption">
              <h5>Cuida de ti y del planeta con Green Market</h5>
              <p>
                Nuestra misión es brindarte una amplia variedad de productos ecológicos y sostenibles.
              </p>
              <a href="#" class="btn btn-outline-success" type="submit">Únete a nosotros</a>
            </div>
          </div>
          <div class="carousel-item ">
            <img src="{% static 'img/carrusel2.png' %}" class="d-block w-100" alt="">
            <div class="carousel-caption">
              <h5>Cuida de ti y del planeta con Green Market</h5>
              <p>
                Te invitamos a unirte a nosotros en la búsqueda de un mundo más saludable.
              </p>
              <a href="#" class="btn btn-outline-success" type="submit">Únete a nosotros</a>
            </div>
          </div>
          <div class="carousel-item ">
            <img src="{% static 'img/carrusel3.png' %}" class="d-block w-100" alt="">
            <div class="carousel-caption">
              <h5>Cuida de ti y del planeta con Green Market</h5>
              <p>
                Donde cuidar de ti mismo y del planeta van de la mano.
              </p>
              <a href="#" class="btn btn-outline-success" type="submit">Únete a nosotros</a>
            </div>
          </div>
  
          <div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselE" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselE" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>
      </div>  
  
      <section class="about section-padding">
            <div class="container">
              <div class="row">
                <div class="col-lg-4 col-md-12 col-12">
                  <div class="about-img">
                    <img src="{% static 'img/gmlogo.png' %} " class="img-fluid" alt="">
                  </div>
                </div>
                <div class="col-lg-8 col-md-12 col-12 ps-lg-5">
                  <div class="about-text">
                    <h2>La Importancia de Ser Sustentable para un Futuro Mejor</h2>
                    <p>Green Market te ofrece una amplia variedad de productos ecológicos y sostenibles, desde alimentos frescos y saludables hasta productos de cuidado personal y artículos para el hogar respetuosos con el medio ambiente. Nuestros productos cumplen con altos estándares de calidad y sostenibilidad, lo que te permite tomar decisiones conscientes y responsables. Únete a nosotros en nuestro compromiso por un mundo más verde y saludable mientras cuidas de ti y del planeta con Green Market.
                    </p>
                    <a href="#" class="btn btn-outline-success" type="submit">Únete a nosotros</a>
                  </div>
                </div>
              </div>
            </div>
      </section>
  
      <section class="services section-padding">
  
            <div class="container">
              <div class="row">
                <div class="col-md-12">
                  <div class="section-header text-center">
                    <h2 class="quienes">¿Quiénes Somos?</h2>
                    <p>Únete a GreenMarket, donde la tecnología se encuentra con la conciencia ecológica. Somos más que una plataforma comercial; somos una iniciativa comprometida con un mañana más verde. En un mundo donde cada elección cuenta, te invitamos a formar parte de nuestro movimiento, cambiando la forma en que compramos y vendemos. Descubre quiénes somos y únete a nosotros en el viaje hacia un futuro más sostenible y próspero.</p>
                  </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="carta col-12 col-md-12 col-lg-6">
                  <div class="card text-black text-center bg-warning pb-2">
                    <div class="card-body">
                      <i class="bi bi-laptop"></i>
                      <h3 class="card-title">Visión</h3>
                      <p class="lead">Ser la plataforma líder a nivel global que conecta a productores, consumidores y empresas comprometidos con un estilo de vida sustentable. Buscamos ser pioneros en la promoción de prácticas ecológicas y consumo responsable, contribuyendo así a un planeta más saludable y equitativo.</p>
                    </div>
                  </div>
                </div>
  
                <div class="col-12 col-md-12 col-lg-6">
                  <div class="card text-black text-center bg-warning pb-2">
                    <div class="card-body">
                      <i class="bi bi-laptop"></i>
                      <h3 class="card-title">Misión</h3>
                      <p class="lead">Facilitar un mercado digital sostenible que promueva la comercialización de productos ecológicos y fomente la conciencia ambiental. En GreenMarket, nos esforzamos por ofrecer una experiencia única, conectando a comunidades alrededor del mundo y apoyando a aquellos que comparten nuestra visión de un futuro más verde. Nuestra misión es inspirar y capacitar a individuos y empresas para que tomen decisiones de compra conscientes y sostenibles.</p>
                    </div>
                  </div>
                </div>

              <div class="row">
                <div class="col-md-12">
                  <div class="section-header text-center">
                    <h2>Transforma tu Consumo, Transforma el Mundo con GreenMarket</h2>
                    <h5>Descubre la Importancia de Ser Ecológico y Únete a un Futuro Sustentable</h5>
                    <p>En Green Market, no solo te ofrecemos una amplia gama de productos ecológicos y sostenibles, sino también una experiencia de compra única. Nuestros servicios van más allá de la simple adquisición de productos.</p>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="carta col-12 col-md-12 col-lg-4">
                  <div class="card text-black text-center bg-warning pb-2">
                    <div class="card-body">
                      <i class="bi bi-laptop"></i>
                      <h3 class="card-title">Redefiniendo Tu Impacto Ambiental</h3>
                      <p class="lead">Cada elección de compra tiene un impacto, y en GreenMarket, creemos que esos impactos pueden ser positivos. Al elegir productos ecológicos, estás contribuyendo directamente a la reducción de la huella de carbono y apoyando prácticas responsables. Es hora de redefinir la forma en que consumimos y ser conscientes de cómo nuestras elecciones diarias pueden moldear un futuro más sostenible.</p>
                    </div>
                  </div>
                </div>
  
                <div class="col-12 col-md-12 col-lg-4">
                  <div class="card text-black text-center bg-warning pb-2">
                    <div class="card-body">
                      <i class="bi bi-laptop"></i>
                      <h3 class="card-title">Apoya Productores Locales y Fomenta la Economía Sustentable</h3>
                      <p class="lead">GreenMarket no solo es una plataforma de compras; es un respaldo a los productores locales comprometidos con prácticas sostenibles. Al elegir productos de GreenMarket, estás apoyando directamente a agricultores y artesanos locales, fomentando una economía circular y reduciendo la huella del transporte. Tu elección importa, y con GreenMarket, estás respaldando comunidades y contribuyendo al crecimiento de una economía más sostenible.</p>
                    </div>
                  </div>
                </div>
  
                <div class="col-12 col-md-12 col-lg-4">
                  <div class="card text-black text-center bg-warning pb-2">
                    <div class="card-body">
                      <i class="bi bi-laptop"></i>
                      <h3 class="card-title">Cuida de tu Hogar y del Planeta a la Vez</h3>
                      <p class="lead">Ser ecológico no solo beneficia al planeta, sino también a tu hogar. Los productos en GreenMarket están diseñados para ser amigables con el medio ambiente y, al mismo tiempo, proporcionar la calidad que tu hogar merece. Desde alimentos frescos y saludables hasta productos de cuidado personal y limpieza, cada compra en GreenMarket es una inversión en la salud de tu hogar y del planeta. Únete a nosotros y descubre cómo cuidar de ambos puede ser tan simple como cambiar tu forma de comprar.</p>
                    </div>
                  </div>
                </div>
        </section>
  
      <section>
  
      </section>
    
    {% endblock %}

    <footer>
      <p>Derechos de autor ©2023 Green Market. Todos los derechos reservados. El contenido de este sitio web, incluyendo textos, imágenes, gráficos y logotipos, está protegido por las leyes de derechos de autor y propiedad intelectual. Queda estrictamente prohibida la reproducción, distribución o cualquier otro uso no autorizado de cualquier material de este sitio sin el permiso por escrito de Green Market.</p>
    </footer>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</body>

</html>

Greenmarket2.0/Greenmarket/crud/templates/carrito.html
<div class="alert alert-primary" role="alert">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="row" colspan="3" class="tex-center">CARRITO</th>
            </tr>
            <tr>
                <th scope="col">NOMBRE</th>
                <th scope="col">PRECIO</th>
                <th scope="col">CANTIDAD</th>
            </tr>
        </thead>
        <tbody>
            {% if request.session.carrito.items %}
            {% for key, value in request.session.carrito.items %}
            <tr>
                <td>{{value.nombre}}</td>
                <td>{{value.precio}}</td>
                <td>{{value.acumulado}}
                    <a href="{% url 'agregar' value.producto_id %}" class="badge btn btn-dark badge-dark">+</a>
                    <a href="{% url 'restar' value.producto_id %}" class="badge btn btn-dark badge-dark">-</a>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">
                    <div class="alet alert-danger text center">Sin Productos</div>
                </td>
            </tr>
            {% endif %}
            <tr>
                <th scope="row">Total:</th>
                <th colspan="2">${{total_carrito}}</th>
            </tr>
        </tbody>
    </table>
    <hr>
</div>
<div class="row" text center>
    <div class="col-6"><a href="{% url 'limpiar' %}" class="btn btn-danger">Limpiar</a></div>
    <div class="col-6"><a href="{% url 'orden' %}" class="btn btn-success">Guardar</a></div>
</div>

Greenmarket2.0/Greenmarket/crud/templates/cliente.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>perfil {{request.user.tipo_perfil}}</title>
</head>

<body>
    <h1>Perfil del Cliente</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Guardar">


        <a href="/">Inicio</a>
        <script src="{% static 'js/logout_timer.js' %}"></script>
</body>

Greenmarket2.0/Greenmarket/crud/templates/crear_producto.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Producto</title>
    <a href="javascript:history.back()">Volver atrás</a>
</head>

<body>
    <h1>Crear Producto</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Guardar">
    </form>
    <script src="{% static 'js/logout_timer.js' %}"></script>
</body>

</html>

Greenmarket2.0/Greenmarket/crud/templates/trueque.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trueque</title>
    <a href="/">home</a>
</head>

<body>
    <!-- Aquí tu contenido actual -->
    <h1>Bienvenido al Trueque</h1>

    <!-- Muestra el formulario -->
    <div>
        <h2>Solicitar Trueque</h2>
        <form method="post">
            {% csrf_token %}
            <label for="id_origen">Origen:</label>
            {{ form.origen }}
            <label for="id_destino">Destino:</label>
            {{ form.destino }}
            <!-- Agrega los demás campos del formulario -->
            <label for="id_descripcion">Descripción:</label>
            {{ form.descripcion }}
            <label for="id_cant_recibida">Cantidad Recibida:</label>
            {{ form.cant_recibida }}
            <label for="id_cant_enviada">Cantidad Enviada:</label>
            {{ form.cant_enviada }}
            <label for="itrueque">Solicitante del trueque:</label>
            {{ form.itrueque }}
            <label for="dtrueque">Receptor del trueque:</label>
            {{ form.dtrueque }}
            <label for="fechatrueque">Fecha de la solicitud:</label>
            {{ form.fecha_trueque }}
            <label for="id_prod_enviado">Producto que se ofrece:</label>
            <select name="prod_enviado" id="id_prod_enviado">
                {% for option in form.prod_enviado.field.queryset %}
                <option value="{{ option.id }}">{{ option.nombre }}</option>
                <!-- Reemplaza 'nombre' por el nombre del campo que quieras mostrar -->
                {% endfor %}
            </select>
            <label for="id_prod_recibido">Producto que se solicita:</label>
            <select name="prod_recibido" id="id_prod_recibido">
                {% for option in form.prod_recibido.field.queryset %}
                <option value="{{ option.id }}">{{ option.nombre }}</option>
                <!-- Reemplaza 'nombre' por el nombre del campo que quieras mostrar -->
                {% endfor %}
            </select>
            <!-- Continúa con el resto de los campos -->
            <button type="submit">Enviar Solicitud de Trueque</button>
        </form>
    </div>
</body>

</html>